### ISSUE TITLE
Agenda for General Meeting

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml#91]
## Agenda for 28/5/2019 Meeting

-  _Brief_ status report on core working group's progress
- Distinguishing Chemistry from Math (from a Chemistry CG)
- Adding some semantic info to presentation MathML (#64, #68, #79, #80, #84, ???)
  -  @NSoiffer's report on a discussion with James Nurthen of ARIA group
- Indicating where insertion cursor or selection is (from [Murray Sargent's blog post](https://blogs.msdn.microsoft.com/murrays/2017/03/19/editing-math-using-mathml-for-speech/))

**Comment by fred-wang** [comment]
Just for reference, I deleted a comment on #8, but this was an agenda for an old general meeting:

## Topics for 12/3/19 general meeting
* [ ] [TPAC meeting F2F](https://www.w3.org/2002/09/wbs/1/CGsTPAC2019/)? (Sept in Japan)
* [ ] Specs/Content MathML: #47
* [ ] Extensions to `semantics`: #68 
* [ ] Continue discussion on presentation "roles": #64

**Comment by NSoiffer** [comment]
## Agenda for 16/7/2019 Meeting

-  _Brief_ status report on core working group's progress
-  TPAC meeting F2F? (Sept in Japan)
-  Full Spec issues (#108)
    - process & final formats
    - relationship to/referencing core spec
- Continue discussion -- adding some semantic info to presentation MathML (#64, #68, #79, #80, #84, #93, ???)
- Indicating where insertion cursor or selection is (from [Murray Sargent's blog post](https://blogs.msdn.microsoft.com/murrays/2017/03/19/editing-math-using-mathml-for-speech/))

**Comment by NSoiffer** [comment]
## Agenda for 6/8/2019 Meeting

-  _Brief_ status report on core working group's progress
- Indicating where insertion cursor or selection is (from [Murray Sargent's blog post](https://blogs.msdn.microsoft.com/murrays/2017/03/19/editing-math-using-mathml-for-speech/))
- Continue discussion -- adding some semantic info to presentation MathML (#64, #68, #79, #80, #84, #93, ???)

**Comment by NSoiffer** [comment]
## Agenda for 10/9/2019 Meeting

- Continue discussion -- adding some semantic info to presentation MathML (#64, #68, #79, #80, #84, #93, ???)
- Path(s) to moving forward on semantics

**Comment by NSoiffer** [comment]
## Agenda for 8/10/2019 Meeting

- Discussion of @samdooley contribution (#141) focused on the semantics of symbols ([this google sheet](https://docs.google.com/spreadsheets/d/1ebOkl7Gckfk5g6Dc4C8bpGZtSxLnGwpOHqAwwON0-nI/edit#gid=135098649)).
- Discussion of @davidfrarmer's followup on semantics and calculus (also #141, and [this google doc)](https://docs.google.com/document/d/1cZnff5_fi_ucNyZ1ex2msmJLE55FAZD-QInkLYe8xiE)

**Comment by NSoiffer** [comment]
## Agenda for 15/10/2019 Meeting

Continuation from previous week, including an update of @samdooley's spreadsheet...

- Discussion of @samdooley contribution (#141) focused on the semantics of symbols ([this google sheet](https://docs.google.com/spreadsheets/d/1ebOkl7Gckfk5g6Dc4C8bpGZtSxLnGwpOHqAwwON0-nI/edit#gid=135098649)).
- Discussion of @davidfrarmer's followup on semantics and calculus (also #141, and [this google doc)](https://docs.google.com/document/d/1cZnff5_fi_ucNyZ1ex2msmJLE55FAZD-QInkLYe8xiE)

**Comment by NSoiffer** [comment]
## Agenda for 12/11/2019 Meeting

Brief update on Core progress

Continuation from previous meeting, including any updates to @samdooley  or @davidfarmer spreedsheets.

- Discussion of @samdooley contribution (#141) focused on the semantics of symbols ([this google sheet](https://docs.google.com/spreadsheets/d/1ebOkl7Gckfk5g6Dc4C8bpGZtSxLnGwpOHqAwwON0-nI/edit#gid=135098649)).
- Discussion of @davidfrarmer's followup on semantics and calculus (also #141, and [this google doc)](https://docs.google.com/document/d/1cZnff5_fi_ucNyZ1ex2msmJLE55FAZD-QInkLYe8xiE)

- Discuss Neil's idea of adding subject area to `<math>` and potentially saying how default semantics change based on that. [Hopefully Neil writes something up and provides a link...]

**Comment by NSoiffer** [comment]
## Agenda for 19/11/2019 Meeting

Continuation from previous meeting.

David Farmer and Neil Soiffer will hopefully have some documents for discussion. Sam Dooley might 
have an update to his contribution (#141) focused on the semantics of symbols ([this google sheet](https://docs.google.com/spreadsheets/d/1ebOkl7Gckfk5g6Dc4C8bpGZtSxLnGwpOHqAwwON0-nI/edit#gid=135098649)).

**Comment by NSoiffer** [comment]
## Agenda for 02/12/2019 Meeting

* Questions from George Kerscher:
  * Chemistry semantics and what support does the MathML CG need from the Chemistry CG?
  * What is the expected timeline for MathML support in Chromium? This relates to the plans to move the MathML CG to a formal W3C Working Group. The  Igalia fork of Chromium with the current implementation is available now, but when would this begin to be included in nightly builds of Chrome proper?
  * The publishers are using MathML right now and it is unclear how this is working in Reading Systems and with screen readers.
  * There is also the issue of speaking MathML in the Read Aloud functions, which may relate to the need for alt text in an image or in the MathML alt-text attribute.
  *What should be our best practice set of recommendation we put to the publishers? VitalSource is recommending MathML with alt-text attribute carrying the textual description.
  *Now that we have MathML out of WordToEPUB, the output should be in alignment with our front runner for the best practice recommendation. Right now, there is LaTex output in the annotation, which Volker thinks is great. We just want to follow the best practice recommendation in this tool.

David Farmer and Neil Soiffer have updates on some documents for discussion:
* David: [google doc](https://docs.google.com/document/d/1cZnff5_fi_ucNyZ1ex2msmJLE55FAZD-QInkLYe8xiE)
* Neil: [google doc](https://docs.google.com/document/d/1NrPFIgxt6FNAOoWzSunI71auADfssCGkiAuDso7RI6s/edit?usp=sharing)
* Sam Dooley updates? [google sheet](https://docs.google.com/spreadsheets/d/1ebOkl7Gckfk5g6Dc4C8bpGZtSxLnGwpOHqAwwON0-nI/edit#gid=135098649)

**Comment by NSoiffer** [comment]
## Agenda for 17/12/2019 Meeting

David Farmer and Neil Soiffer have updates on some documents for discussion:
* David: [google doc](https://docs.google.com/document/d/1cZnff5_fi_ucNyZ1ex2msmJLE55FAZD-QInkLYe8xiE)
* Neil: [google doc](https://docs.google.com/document/d/1NrPFIgxt6FNAOoWzSunI71auADfssCGkiAuDso7RI6s/edit?usp=sharing)
* Sam Dooley updates? [google sheet](https://docs.google.com/spreadsheets/d/1ebOkl7Gckfk5g6Dc4C8bpGZtSxLnGwpOHqAwwON0-nI/edit#gid=135098649)

**Comment by NSoiffer** [comment]
## Agenda for 14/1/20 Meeting

* Naming scheme for mathrole values
  * Some open math dictionary?  content MathML? something else?
* Where does the mathrole go?
  * does `mathrole='transpose'` go on the 't' or the 'msup' or somewhere else?
* What should be done when there is no mathrole value yet? 
  * e.g., Neil's `alt` and `data-matlab='...'` idea\
